[package]
name = "nvptxglue-example"
version = "0.0.0"
edition = "2018"

#[workspace]
#members = ["kernels"]

[lib]
name = "nvptxglue_example"
path = "lib.rs"

[build-dependencies]
nvptxglue = { path = "../nvptxglue" }
